<?php

/**
 * @file
 * Contains islandora_lite_defaults.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function islandora_lite_defaults_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the islandora_lite_defaults module.
    case 'help.page.islandora_lite_defaults':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module genrate core component for DSU Islandora Lite Stacks') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function islandora_lite_defaults_theme() {
  return [
    'islandora_lite_defaults' => [
      'render element' => 'children',
    ],
  ];
}
